my_file = open ("Numbers", "w")
my_file.write(str(3))
my_file.write("\n")
my_file.write(str(45))
my_file.write("\n")
my_file.write(str(83))
my_file.write("\n")
my_file.write(str(21))
my_file.close()